### ISSUE TITLE
StackOverflowException in MarkdownParser when running sbt under Java 8.

### ISSUE THREAD

**Issue by metasim** [sbt/website#143]
As of 7f989416ee0fda2e3558343cc90cf971d32a007b, running `makeSite` causes a `StackOverflowException` in:

    com.tristanhunt.knockoff.ChunkParser$$anon$1.findEnd(MarkdownParsing.scala:270)

Obviously not really a bug in the documentation, but logging since the docs can't be built until fixed.

Top of the stack trace:
```
java.lang.StackOverflowError
	at java.util.regex.Pattern.compile(Pattern.java:1683)
	at java.util.regex.Pattern.<init>(Pattern.java:1351)
	at java.util.regex.Pattern.compile(Pattern.java:1028)
	at scala.util.matching.Regex.<init>(Regex.scala:153)
	at scala.collection.immutable.StringLike$class.r(StringLike.scala:224)
	at scala.collection.immutable.StringOps.r(StringOps.scala:31)
	at scala.collection.immutable.StringLike$class.r(StringLike.scala:213)
	at scala.collection.immutable.StringOps.r(StringOps.scala:31)
	at com.tristanhunt.knockoff.ChunkParser$$anon$1.findEnd(MarkdownParsing.scala:261)
	at com.tristanhunt.knockoff.ChunkParser$$anon$1.findEnd(MarkdownParsing.scala:270)
	at com.tristanhunt.knockoff.ChunkParser$$anon$1.findEnd(MarkdownParsing.scala:270)
	at com.tristanhunt.knockoff.ChunkParser$$anon$1.findEnd(MarkdownParsing.scala:270)
```

**Comment by metasim** [comment]
Context:

```
> about
[info] This is sbt 0.13.7
[info] The current project is {file:/Users/sfitch/Coding/OSS/sbt-website/}root 0.1-SNAPSHOT
[info] The current project is built against Scala 2.10.4
[info] Available Plugins: sbt.plugins.IvyPlugin, sbt.plugins.JvmPlugin, sbt.plugins.CorePlugin, sbt.plugins.JUnitXmlReportPlugin, sbtmeow.SbtMeowPlugin, sbtsh.ShPlugin, net.virtualvoid.sbt.graph.Plugin, com.typesafe.sbt.SbtSite, com.typesafe.sbt.SbtGhPages, com.typesafe.sbt.SbtGit
```

```
> plugins
In file:/Users/sfitch/Coding/OSS/sbt-website/
	sbt.plugins.IvyPlugin: enabled in root
	sbt.plugins.JvmPlugin: enabled in root
	sbt.plugins.CorePlugin: enabled in root
	sbt.plugins.JUnitXmlReportPlugin: enabled in root
	sbtmeow.SbtMeowPlugin: enabled in root
	sbtsh.ShPlugin: enabled in root
```

**Comment by metasim** [comment]
Something else is going on, as I still have the problem when checking out as far back as 91e7894e5b1e61c12f8fa71cbd38c0389f7b3ff8 (Feb 17).

**Comment by eed3si9n** [comment]
I'm not seeing the problem. I just pushed the site right now to check.

**Comment by metasim** [comment]
sbt output.

```
[info] generated /Users/sfitch/Coding/OSS/sbt-website/target/redirect/Examples/Advanced-Command-Example.html that links to ../Advanced-Command-Example.html
Error while processing /Users/sfitch/Coding/OSS/sbt-website/src/reference/01-General-Info/04-Bintray-For-Plugins.md
[info] Loading site data… done
[info] Compiling site…
[info]       create  [0.00s]  ../../target/nanoc/assets/arc.js
[info]       create  [0.00s]  ../../target/nanoc/assets/bootstrap-theme.min.css
[info]       create  [0.00s]  ../../target/nanoc/assets/bootstrap.min.js
[info]       create  [0.00s]  ../../target/nanoc/assets/bootstrap_style.min.css
[info]       create  [0.00s]  ../../target/nanoc/assets/community-support.svg
[info]       create  [0.08s]  ../../target/nanoc/community.html
[info]       create  [0.01s]  ../../target/nanoc/documentation.html
[info]       create  [0.01s]  ../../target/nanoc/download.html
[info]       create  [0.00s]  ../../target/nanoc/assets/favicon.ico
[info]       create  [0.00s]  ../../target/nanoc/assets/github-logo-teal.png
[info]       create  [0.00s]  ../../target/nanoc/assets/github-logo.png
[info]       create  [0.00s]  ../../target/nanoc/assets/glyphicons-halflings-regular.svg
[info]       create  [0.01s]  ../../target/nanoc/index.html
[info]       create  [0.00s]  ../../target/nanoc/assets/jquery.min.js
[info]       create  [0.00s]  ../../target/nanoc/assets/stylesheet.css
[info]       create  [0.00s]  ../../target/nanoc/assets/twitter-logo-teal.png
[info]       create  [0.00s]  ../../target/nanoc/assets/twitter-logo-white.png
[info]       create  [0.00s]  ../../target/nanoc/assets/typesafe-logo-reverse.svg
[info]       create  [0.00s]  ../../target/nanoc/assets/typesafe_color_reverse.svg
[info]       create  [0.00s]  ../../target/nanoc/assets/typesafe_full_color.svg
[info]       create  [0.00s]  ../../target/nanoc/assets/typesafe_icon_full_color.svg
[info]       create  [0.00s]  ../../target/nanoc/assets/typesafe_icon_reverse.svg
[info]       create  [0.00s]  ../../target/nanoc/assets/typesafe_reverse.svg
[info]       create  [0.00s]  ../../target/nanoc/assets/typesafe_sbt_color_reverse_png.png
[info]       create  [0.00s]  ../../target/nanoc/assets/typesafe_sbt_color_reverse_svg.svg
[info]       create  [0.00s]  ../../target/nanoc/assets/typesafe_sbt_png.png
[info]       create  [0.00s]  ../../target/nanoc/assets/typesafe_sbt_reverse.svg
[info]       create  [0.00s]  ../../target/nanoc/assets/typesafe_sbt_reverse_png.png
[info]       create  [0.00s]  ../../target/nanoc/assets/typesafe_sbt_reverse_svg.svg
[info]       create  [0.00s]  ../../target/nanoc/assets/typesafe_sbt_svg.svg
[info]       create  [0.00s]  ../../target/nanoc/assets/wrench-1000-center-navy.png
[info] 
[info] Site compiled in 0.22s.
Error while processing java.lang.StackOverflowError
[trace] Stack trace suppressed: run last reference:mappings for the full output.
[trace] Stack trace suppressed: run last tutorial:mappings for the full output.
[error] (reference:mappings) java.lang.StackOverflowError
[error] (tutorial:mappings) java.lang.StackOverflowError
```

**Comment by metasim** [comment]
Note: I installed all the ruby bits per README.md.

**Comment by eed3si9n** [comment]
I'm using Java 7. -Xmx2G -XX:MaxPermSize=512M -Dfile.encoding=UTF-8.

**Comment by metasim** [comment]
Me: 
java version "1.8.0_40"
Java(TM) SE Runtime Environment (build 1.8.0_40-b25)

Will try with your options and Java 7.

**Comment by metasim** [comment]
Works with Java 7! Issue should probably be filed against `sat-site`
