### ISSUE TITLE
knockoff markdown parser StackOverflowError

### ISSUE THREAD

**Issue by xuwei-k** [sbt/website#373]
https://travis-ci.org/sbt/website/builds/246012793#L1904

```
java.lang.StackOverflowError
	at java.util.regex.Pattern.sequence(Pattern.java:2051)
	at java.util.regex.Pattern.expr(Pattern.java:1996)
	at java.util.regex.Pattern.compile(Pattern.java:1696)
	at java.util.regex.Pattern.<init>(Pattern.java:1351)
	at java.util.regex.Pattern.compile(Pattern.java:1028)
	at scala.util.matching.Regex.<init>(Regex.scala:186)
	at scala.collection.immutable.StringLike$class.r(StringLike.scala:224)
	at scala.collection.immutable.StringOps.r(StringOps.scala:31)
	at scala.collection.immutable.StringLike$class.r(StringLike.scala:213)
	at scala.collection.immutable.StringOps.r(StringOps.scala:31)
	at com.tristanhunt.knockoff.ChunkParser$$anon$1.findEnd(MarkdownParsing.scala:261)
	at com.tristanhunt.knockoff.ChunkParser$$anon$1.findEnd(MarkdownParsing.scala:270)
	at com.tristanhunt.knockoff.ChunkParser$$anon$1.findEnd(MarkdownParsing.scala:270)
	at com.tristanhunt.knockoff.ChunkParser$$anon$1.findEnd(MarkdownParsing.scala:270)
```

I think this issue fixed https://github.com/foundweekends/knockoff/commit/8667172c62d2c6fad055c98bc065aae637aae3ad (4 years ago!). but sbt-site plugin pulls old knockoff dependency 😭 

![sbt-site](https://user-images.githubusercontent.com/389787/27515218-804527ba-59d9-11e7-8f64-0e994a7cff1b.png)

**Comment by xuwei-k** [comment]
related https://github.com/sbt/website/issues/143

**Comment by ashawley** [comment]
Looks like Travis failed to switch to oraclejdk7:

```
$ jdk_switcher use oraclejdk7
Switching to Oracle JDK7 (java-7-oracle), JAVA_HOME will be set to /usr/lib/jvm/java-7-oracle
update-java-alternatives: directory does not exist: /usr/lib/jvm/java-7-oracle
```

But yeah, be better to just fix the knockoff bug in Java 8.
